"""create_recoveriq_initial_schema

Revision ID: 38326ce05b59
Revises: 
Create Date: 2026-08-28 21:08:37.906189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38326ce05b59'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_customer_id', sa.String(length=128), nullable=False),
    sa.Column('razorpay_customer_id', sa.String(length=128), nullable=True),
    sa.Column('email_masked', sa.String(length=255), nullable=True),
    sa.Column('phone_masked', sa.String(length=64), nullable=True),
    sa.Column('risk_tier', sa.String(length=32), nullable=False),
    sa.Column('total_payments_count', sa.Integer(), nullable=False),
    sa.Column('failed_payments_count', sa.Integer(), nullable=False),
    sa.Column('recovered_payments_count', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_customer_id'),
    sa.UniqueConstraint('razorpay_customer_id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('external_subscription_id', sa.String(length=128), nullable=True),
    sa.Column('razorpay_subscription_id', sa.String(length=128), nullable=True),
    sa.Column('plan_name', sa.String(length=128), nullable=False),
    sa.Column('billing_cadence', sa.String(length=32), nullable=False),
    sa.Column('recurring_amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('recurring_amount >= 0', name='chk_subscription_recurring_amount_non_negative'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_subscription_id')
    )
    op.create_index('idx_subscriptions_customer_id', 'subscriptions', ['customer_id'], unique=False)
    op.create_index('idx_subscriptions_status', 'subscriptions', ['status'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=True),
    sa.Column('external_order_id', sa.String(length=128), nullable=True),
    sa.Column('razorpay_order_id', sa.String(length=128), nullable=True),
    sa.Column('razorpay_invoice_id', sa.String(length=128), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('amount >= 0', name='chk_payment_amount_non_negative'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_invoice_id'),
    sa.UniqueConstraint('razorpay_order_id')
    )
    op.create_index('idx_payments_customer_id', 'payments', ['customer_id'], unique=False)
    op.create_index('idx_payments_status_created', 'payments', ['status', 'created_at'], unique=False)
    op.create_index('idx_payments_subscription_id', 'payments', ['subscription_id'], unique=False)
    op.create_table('payment_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=128), nullable=True),
    sa.Column('payment_method', sa.String(length=32), nullable=True),
    sa.Column('payment_method_sub_type', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_source', sa.String(length=64), nullable=True),
    sa.Column('error_step', sa.String(length=64), nullable=True),
    sa.Column('error_reason', sa.String(length=128), nullable=True),
    sa.Column('error_description', sa.Text(), nullable=True),
    sa.Column('initiated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount >= 0', name='chk_payment_attempt_amount_non_negative'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id', 'attempt_number', name='uq_payment_attempt_seq'),
    sa.UniqueConstraint('razorpay_payment_id')
    )
    op.create_index('idx_payment_attempts_error_reason', 'payment_attempts', ['error_reason'], unique=False)
    op.create_index('idx_payment_attempts_payment_id', 'payment_attempts', ['payment_id'], unique=False)
    op.create_table('payment_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('razorpay_event_id', sa.String(length=128), nullable=True),
    sa.Column('payload', postgresql.JSONB().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('processing_status', sa.String(length=32), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('razorpay_event_id')
    )
    op.create_index('idx_payment_events_payment_id', 'payment_events', ['payment_id'], unique=False)
    op.create_index('idx_payment_events_type_status', 'payment_events', ['event_type', 'processing_status'], unique=False)
    op.create_table('recovery_cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('recovery_stage', sa.String(length=32), nullable=False),
    sa.Column('amount_at_risk', sa.BigInteger(), nullable=False),
    sa.Column('recovered_amount', sa.BigInteger(), nullable=False),
    sa.Column('total_attempts_count', sa.Integer(), nullable=False),
    sa.Column('max_allowed_attempts', sa.Integer(), nullable=False),
    sa.Column('latest_failure_reason', sa.String(length=128), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('next_action_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_reason', sa.String(length=64), nullable=True),
    sa.Column('metadata', postgresql.JSONB().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('amount_at_risk >= 0', name='chk_case_amount_at_risk_non_negative'),
    sa.CheckConstraint('recovered_amount <= amount_at_risk', name='chk_case_recovered_not_exceed_risk'),
    sa.CheckConstraint('recovered_amount >= 0', name='chk_case_recovered_amount_non_negative'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recovery_cases_customer_id', 'recovery_cases', ['customer_id'], unique=False)
    op.create_index('idx_recovery_cases_opened_at', 'recovery_cases', ['opened_at'], unique=False)
    op.create_index('idx_recovery_cases_payment_id', 'recovery_cases', ['payment_id'], unique=False)
    op.create_index('idx_recovery_cases_status_next_action', 'recovery_cases', ['status', 'next_action_due_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('recovery_case_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('previous_state', postgresql.JSONB().with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('new_state', postgresql.JSONB().with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('metadata', postgresql.JSONB().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_case_id', 'audit_logs', ['recovery_case_id'], unique=False)
    op.create_index('idx_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_logs_event_type', 'audit_logs', ['event_type'], unique=False)
    op.create_table('ml_predictions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recovery_case_id', sa.Uuid(), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('recovery_probability', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('predicted_channel', sa.String(length=32), nullable=True),
    sa.Column('predicted_delay_hours', sa.Integer(), nullable=True),
    sa.Column('feature_vector_snapshot', postgresql.JSONB().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('predicted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('recovery_probability >= 0.0000 AND recovery_probability <= 1.0000', name='chk_ml_recovery_probability_range'),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ml_predictions_case_id', 'ml_predictions', ['recovery_case_id'], unique=False)
    op.create_index('idx_ml_predictions_model_version', 'ml_predictions', ['model_name', 'model_version'], unique=False)
    op.create_table('agent_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recovery_case_id', sa.Uuid(), nullable=False),
    sa.Column('ml_prediction_id', sa.Uuid(), nullable=True),
    sa.Column('agent_name', sa.String(length=64), nullable=False),
    sa.Column('agent_version', sa.String(length=32), nullable=False),
    sa.Column('prompt_template_version', sa.String(length=32), nullable=False),
    sa.Column('proposed_action_type', sa.String(length=64), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('reasoning_summary', sa.Text(), nullable=False),
    sa.Column('suggested_payload', postgresql.JSONB().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('token_usage', postgresql.JSONB().with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('confidence_score >= 0.0000 AND confidence_score <= 1.0000', name='chk_agent_confidence_score_range'),
    sa.ForeignKeyConstraint(['ml_prediction_id'], ['ml_predictions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_decisions_action_type', 'agent_decisions', ['proposed_action_type'], unique=False)
    op.create_index('idx_agent_decisions_case_id', 'agent_decisions', ['recovery_case_id'], unique=False)
    op.create_index('idx_agent_decisions_decided_at', 'agent_decisions', ['decided_at'], unique=False)
    op.create_index('idx_agent_decisions_ml_prediction_id', 'agent_decisions', ['ml_prediction_id'], unique=False)
    op.create_table('policy_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recovery_case_id', sa.Uuid(), nullable=False),
    sa.Column('agent_decision_id', sa.Uuid(), nullable=True),
    sa.Column('evaluation_result', sa.String(length=32), nullable=False),
    sa.Column('policy_engine_version', sa.String(length=32), nullable=False),
    sa.Column('triggered_rule_code', sa.String(length=64), nullable=True),
    sa.Column('rule_name', sa.String(length=128), nullable=True),
    sa.Column('evaluation_details', postgresql.JSONB().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('decision_reason', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_decision_id'], ['agent_decisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_policy_decisions_agent_decision_id', 'policy_decisions', ['agent_decision_id'], unique=False)
    op.create_index('idx_policy_decisions_case_id', 'policy_decisions', ['recovery_case_id'], unique=False)
    op.create_index('idx_policy_decisions_result', 'policy_decisions', ['evaluation_result'], unique=False)
    op.create_index('idx_policy_decisions_rule_code', 'policy_decisions', ['triggered_rule_code'], unique=False)
    op.create_table('recovery_actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recovery_case_id', sa.Uuid(), nullable=False),
    sa.Column('policy_decision_id', sa.Uuid(), nullable=False),
    sa.Column('action_idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('action_payload', postgresql.JSONB().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['policy_decision_id'], ['policy_decisions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_idempotency_key')
    )
    op.create_index('idx_recovery_actions_case_id', 'recovery_actions', ['recovery_case_id'], unique=False)
    op.create_index('idx_recovery_actions_policy_decision_id', 'recovery_actions', ['policy_decision_id'], unique=False)
    op.create_index('idx_recovery_actions_status_scheduled', 'recovery_actions', ['status', 'scheduled_for'], unique=False)
    op.create_table('action_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recovery_action_id', sa.Uuid(), nullable=False),
    sa.Column('execution_status', sa.String(length=32), nullable=False),
    sa.Column('provider_reference_id', sa.String(length=128), nullable=True),
    sa.Column('provider_status_code', sa.String(length=64), nullable=True),
    sa.Column('failure_reason', sa.String(length=128), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('response_payload_summary', postgresql.JSONB().with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['recovery_action_id'], ['recovery_actions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_action_results_action_id', 'action_results', ['recovery_action_id'], unique=False)
    op.create_index('idx_action_results_provider_ref', 'action_results', ['provider_reference_id'], unique=False)
    op.create_index('idx_action_results_status', 'action_results', ['execution_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_action_results_status', table_name='action_results')
    op.drop_index('idx_action_results_provider_ref', table_name='action_results')
    op.drop_index('idx_action_results_action_id', table_name='action_results')
    op.drop_table('action_results')
    op.drop_index('idx_recovery_actions_status_scheduled', table_name='recovery_actions')
    op.drop_index('idx_recovery_actions_policy_decision_id', table_name='recovery_actions')
    op.drop_index('idx_recovery_actions_case_id', table_name='recovery_actions')
    op.drop_table('recovery_actions')
    op.drop_index('idx_policy_decisions_rule_code', table_name='policy_decisions')
    op.drop_index('idx_policy_decisions_result', table_name='policy_decisions')
    op.drop_index('idx_policy_decisions_case_id', table_name='policy_decisions')
    op.drop_index('idx_policy_decisions_agent_decision_id', table_name='policy_decisions')
    op.drop_table('policy_decisions')
    op.drop_index('idx_agent_decisions_ml_prediction_id', table_name='agent_decisions')
    op.drop_index('idx_agent_decisions_decided_at', table_name='agent_decisions')
    op.drop_index('idx_agent_decisions_case_id', table_name='agent_decisions')
    op.drop_index('idx_agent_decisions_action_type', table_name='agent_decisions')
    op.drop_table('agent_decisions')
    op.drop_index('idx_ml_predictions_model_version', table_name='ml_predictions')
    op.drop_index('idx_ml_predictions_case_id', table_name='ml_predictions')
    op.drop_table('ml_predictions')
    op.drop_index('idx_audit_logs_event_type', table_name='audit_logs')
    op.drop_index('idx_audit_logs_entity', table_name='audit_logs')
    op.drop_index('idx_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('idx_audit_logs_case_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('idx_recovery_cases_status_next_action', table_name='recovery_cases')
    op.drop_index('idx_recovery_cases_payment_id', table_name='recovery_cases')
    op.drop_index('idx_recovery_cases_opened_at', table_name='recovery_cases')
    op.drop_index('idx_recovery_cases_customer_id', table_name='recovery_cases')
    op.drop_table('recovery_cases')
    op.drop_index('idx_payment_events_type_status', table_name='payment_events')
    op.drop_index('idx_payment_events_payment_id', table_name='payment_events')
    op.drop_table('payment_events')
    op.drop_index('idx_payment_attempts_payment_id', table_name='payment_attempts')
    op.drop_index('idx_payment_attempts_error_reason', table_name='payment_attempts')
    op.drop_table('payment_attempts')
    op.drop_index('idx_payments_subscription_id', table_name='payments')
    op.drop_index('idx_payments_status_created', table_name='payments')
    op.drop_index('idx_payments_customer_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index('idx_subscriptions_status', table_name='subscriptions')
    op.drop_index('idx_subscriptions_customer_id', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('customers')
    # ### end Alembic commands ###
